apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dummyapp
    name: dummyapp
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dummyapp
    name: dummyapp
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: dummyapp:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/karmab/dummyapp.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.5
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: -2_DVyJIdjafGrYiFl5j
      type: GitHub
    - generic:
        secret: COu9ugsThkjIIUt3biCI
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dummyapp
    name: dummyapp
  spec:
    replicas: 1
    selector:
      app: dummyapp
      deploymentconfig: dummyapp
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: dummyapp
          deploymentconfig: dummyapp
      spec:
        containers:
        - image: dummyapp:latest
          name: dummyapp
          ports:
          - containerPort: 9000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - dummyapp
        from:
          kind: ImageStreamTag
          name: dummyapp:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: dummyapp
    name: dummyapp
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: dummyapp
      deploymentconfig: dummyapp
  status:
    loadBalancer: {}
kind: List
metadata: {}
